### PR TITLE
fix/task details

### PR DESCRIPTION
**Pull request by blaggacao**
- fix: task detail
- fix: pop up actions

closes: #298
closes: #295
closes: #292

### CODE REVIEW

**Comment by blaggacao** [comment]
> I have just three things to teach: simplicity, patience, compassion. These three are your greatest treasures.   - Lao Tzu 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
@netchampfaris Could you please take a closer look at this? Thx!

**Comment by blaggacao** [comment]
> The important thing is this: to be able at any moment to sacrifice what we are for what we could become.  - Charles Dubois

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Obstacles are those frightful things you see when you take your eyes off your goal.  - Henry Ford

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Our distrust is very expensive.  - Ralph Emerson

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> An invincible determination can accomplish almost anything and in this lies the great distinction between great men and little men.  - Thomas Fuller 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by rmehta** [comment]
rebase?

**Review by AyshaHakeem — CHANGES_REQUESTED** [review]
Please fix the failing tests

**Comment by blaggacao** [comment]
ack, asap

**Comment by netchampfaris** [comment]
@blaggacao 

Dialog action API was broken in frappe-ui, it's now fixed. `close` function was meant to be passed in a object. It's now fixed with https://github.com/frappe/gameplan/commit/6e5268ef619ce205e3966cc7188eea6c341524da
I have also fixed the task assignment issue in https://github.com/frappe/gameplan/commit/ef6589473547dab7f522482aea3931744037a13a

Thanks for your work, this PR can be closed now.

**Comment by blaggacao** [comment]
Tanks a lot!

**Pull request closed without merging**
